default gender: Ambiguous
default age: 20
default race: human
default description: "Who's this asshole?"
max name length: 30
max description length: 300
min age: 5
max age: 150
valid genders:
- female
- male
- ambiguous
valid races:
- human
- droid
weapon threat levels:
  DIAMOND_SWORD: 5
  GOLD_SWORD: 5
  IRON_SWORD: 3
  WOOD_SWORD: 1